# Copyright (C) 2026 Lorris Turpin / 360 Hearts in the Sky
# Licensed under AGPL-3.0 — see LICENSE file for details.
"""
Per-house-pair Parivartana (exchange) interpretations.
======================================================
A specific reading for EVERY house-pair exchange (Maha = beneficial fusion of two
good houses, Khala = mixed/effortful via the 3rd, Dainya = misery via a dusthana
6/8/12). Replaces the old single general-per-type text so any chart's exact
exchange shows text tailored to its two houses.

Keyed by a SORTED (low, high) house-pair tuple. SOURCE: the authored house-learning
study guides (inspired by Ernst Wilhelm's teaching on Parivartana Yogas, per-house-pair
readings), written in the app author's voice. Coverage:
28 Maha + 8 Khala + 30 Dainya = 66 pairs.
"""

MAHA_PAIR_DESC = {
    (1, 2): "Your path and your resources fuse: you can manage many things at once and carry large responsibilities, and the successes that look lucky actually come from real capacity. The self-assurance here is honest, built on genuine competence rather than pretension, so the people who know you rely on you. The 2nd is a house of load, and this exchange converts that load into dependable, respected follow-through.",
    (1, 4): "Your identity and your inner home link into a standing contentment: you know your own needs and can meet them, which keeps you centered and hard to ruffle or manipulate. Because you know your own mind you sidestep the impulsive, reckless mistakes that make others come up short, and the 4th being a house of fortune quietly hands you more than your fair share (you tend to come out ahead at games and windfalls). This is a hidden, felt happiness that follows you through ordinary daily life rather than a public spotlight.",
    (1, 5): "This is the most powerful Maha exchange: your path and your creative intelligence merge so that your mind snaps to the right conclusion as if by magic and you rarely make mistakes. You gravitate to your single greatest gift rather than dabbling in talents, so you shine, gain fame and wealth, and naturally rise above the less focused. In Jaimini this specifically reads as a Raja Yoga, a genuine power-and-success signature, so flag it whenever you see it.",
    (1, 7): "Your forward motion in life runs through partnership and the public: a real gift for connecting with people who love you and lift you as you love them back. The catch is dignity, because the 1st and 7th lords are almost always enemies or neutrals and rarely sit in a natural friend sign, which makes this the weakest Maha pair for happiness. When it is afflicted, watch for relationship stress and a tendency to lose yourself in others.",
    (1, 9): "Your identity is anchored to a path you deeply believe in, and that path actually carries you where you want to go, so life stays on track and you succeed young without wasted searching. The belief works like a fire that will not go out, a core conviction that holds you together through anything negative. This is the best Maha yoga for rescuing an otherwise difficult chart: the theme keeps you afloat through hard years and resurfaces again and again so life steadily improves over time.",
    (1, 10): "Your path fuses with your capacity to act and do great deeds, so you rise to the top of whatever hierarchy you are in and lead naturally, often from childhood. You get positions of power and responsibility simply by being the most capable and trustworthy person for the task. This is a Parashara-type Raja Yoga: it makes you do more, with the only ceiling being how big a bite of life you choose to take on, though doing more does not by itself mean happier.",
    (1, 11): "Your path connects to the house of fulfilled hopes, so you reach the life goal you set, usually through a process rather than overnight, and gain solid income with real recognition from your peers. The 11th is the ultimate house of social success, so this is the exchange that most makes you feel you fit into the world and have filled the niche you were meant to fill. Of all the Maha yogas, this is the one that most delivers a felt sense of social acceptance and arrival.",
    (2, 4): "You are innately happy with your responsibilities and possessions, content to spend your life on whatever carries your name (your home, your holdings, the things you call mine). This is a productive, grounded combination that is strong for wealth and real estate, since it joins the 4th's large share of fortune with the 2nd's accumulated resources. It reads as a reliable good thing you always carry with you.",
    (2, 5): "Your creativity and your accumulated resources link into long-term, sustainable output: you love and create one thing steadily over the long haul and succeed through consistency rather than chasing distractions. Because the 2nd's focus is the healthy day-to-day kind rather than burnout, it compounds across the whole life, so you cultivate more and more and build something to be proud of. It brings caretaking and responsibility, and a knack for getting exactly what you need for the next goal.",
    (2, 7): "You are responsible and genuinely caring toward your partner, treating the relationship as something valuable that is yours to look after rather than to extract from. You give for the partner's sake and are taken care of in return, so you become real friends, and that kind of committed, mutual relationship is a solid cause for happiness. The 2nd's sense of mine here means care and stewardship, never possessiveness or abuse.",
    (2, 9): "This is a big wealth producer where higher wisdom guides what you accumulate: you are steady, responsible, and mature, and you recognize exactly what you should take care of, why, and how it improves everyone's life. Because the 9th is a non-attached, letting-go house, it keeps you from taking on more than you should, so prosperity stays balanced and never collapses from overreach. You know what to expect from things and what to give them, which is why it never bites off more than it can chew.",
    (2, 10): "You make life work by being materially and financially responsible, able to carry the health, possessions, and welfare of many people, not just yourself. With that shouldered responsibility come the wealth, respect, and personal satisfaction of actually fulfilling it. It is a very solid combination that turns capability into both means and standing.",
    (2, 11): "This is a life of increase: the house that gains fuses with the house of what is yours, so you steadily accumulate more of what carries your name (more money, collections, houses, responsibilities, good people, and, if they interest you, fame or power). It runs on a self-reinforcing loop where you learn to see the value in what life affords you, use that value well, and thereby raise the worth of your own life so more accrues. The strength here is reliable, supportive increase rather than spectacular angular power.",
    (4, 5): "Your inner home and your creative self-expression fuse into a deeply nourishing happiness: you are exceptionally good at finding joy in what you do, because the joy itself is the goal. Emotionally secure in your love and creativity, you attract real abundance, making this one of the most prosperous of the 5th-house pairs. It is also the luckiest pair for children, giving more joy and fewer problems with them and lucky breaks even when the child-signifying planets are stressed, and depending on the ascendant it can also form a Raja Yoga.",
    (4, 7): "Your partnership becomes a second safe home: the same contentment that rises in you when you are alone now rises when you are with your partner. Your feelings flow honestly into your actions, so you do the right thing in relationships and end up with a bond that others would call a genuine reason to be happy. The relationship itself is felt as a secure retreat rather than a source of guard and defense.",
    (4, 9): "Wisdom produces happiness here: you are a wise, quietly content person who finds a reason to be happy, and usually needs no reason at all, being settled just by being who you are. It is very fortunate for real estate and abundance, and it keeps you flexible and never stubborn, able to shift viewpoint and hold onto happiness in almost any situation. Even with a hard planet weighing on the 4th, this yoga is the thing that picks you up and gives you the material to become happy through the difficulty.",
    (4, 10): "Your work becomes emotionally compatible with who you are, so your career turns into a safe, secure home where life simply works, and you can be as happy at work as at rest. Parashara names this a yoga for power and success, and because the 10th lord sits in your house of the heart, the work fits your emotional nature, which is exactly what makes room for happiness inside it. It is a strong signature for a life that works and rises.",
    (4, 11): "You feel at home among your peers, groups, and society, so those social spheres become a genuine source of inner happiness rather than strain. It boosts wealth and gains, and because the 11th is the love and reward you receive from the world (including from a spouse), you are happy with the love that comes back to you. Belonging itself becomes one of your safe places.",
    (5, 7): "You have fortune in love and with the public, an easy creative rapport with almost anyone you are with, which makes it ideal for entertainers and politicians. It is a passionate exchange, but it is the weakest of the 5th-house pairs for marriage stability and does not guarantee a good one: when afflicted it can produce serial relationships, too much luck with the opposite sex, or a creativity that keeps wanting another partner. Fortune with children here tends toward abundance in number rather than the close few, and marrying someone you truly love gives a strong cause for happiness when it holds.",
    (5, 9): "This is the most harmonious and balanced of the exchanges, joining creative intelligence with mature wisdom so fortune spreads evenly across wealth, love, children, and satisfying self-expression rather than spiking in one area. It combines the 5th's consistency for when life stays the same with the 9th's wisdom for when life changes, giving you strength where it matters plus the wisdom to let go. It almost always confers innate spiritual wisdom, and while it is not the highest single peak of worldly success, its balance sustains happiness better than any spike.",
    (5, 10): "You act on and do the real work of what you love, fulfilling your creative destiny into satisfaction, prosperity, and wealth, with strong potential for political power. The 6/8 relation here brings constant but lucky change around career and aspirations, so there is always a fresh break to act on and you are never bored or stuck in drudgery. The 10th is a house of increase, so your potential keeps emerging and each iteration is bigger than the last, with no real ceiling on how far it goes.",
    (5, 11): "This is the dedicated wealth pair: abundance, high income, titles, medals, and honors that brand you as an important and respected person. Unlike the effortless luck of the angle pairs, the reward here is earned gradually through a process, steadily living your creative life and getting better and more successful over time, like the master performer who improves with every appearance. You continue to excel in your creative destiny and reach mastery progressively, and the whole climb itself feels satisfying.",
    (7, 9): "Your relationships run on wisdom rather than raw passion, which is exactly why this is generally nicer than the 5th and 7th version: passion is what gets people into trouble, and the maturity here keeps you clear-headed where people usually get most confused. It is strongly indicated for one really good, lucky marriage, and it makes you fortunate with the public and skilled at handling it wisely. It is happy with children and grandchildren, propagating with purpose and wisdom, and it is both happiness-giving and wealth-producing.",
    (7, 10): "Two angles meet here with no trine involved, so this reads as a very busy person with plenty of causes for happiness: successes, good relationships, public appreciation, power, and business and financial standing. The catch is that it is not quite as happy as the angle-and-trine combinations, because you are less attuned to and less invested in things you merely do than in who you truly are. If a trine lord (1st, 5th, or 9th) also joins in, the cause for happiness starts to include your real self and the felt gap closes.",
    (7, 11): "You draw fortune from the benefits gained through the public and through relationships, and you have a knack for playing your dealings so that everyone involved benefits, which is the only lasting way to gain from people. You benefit from your spouse, from the public, and from your sheer ability to relate, making for a very fortunate life among people. Gains flow to you through partnership, and you tend to see the gift in every relationship turn of events.",
    (9, 10): "You find the way to live your life in accordance with what you truly believe and truly want to do, acting on your higher wisdom to build a genuinely good life. For most ascendants this creates a Raja Yoga and gives more power in general, along with strong prosperity, wealth, and the respect and auxiliaries (like a good marriage) that follow. It is a deeply dharmic exchange where wisdom sets the direction and action carries it out.",
    (9, 11): "This is big for a good, large income, and it moves toward your goals with mature, patient progress rather than the fast, exuberant rush of the 5th: you simply pick the right path to begin with and understand what you are doing. It steadily produces success and standing, and because the 11th is a great house of respect and nothing earns more respect than genuine wisdom, you are respected for your understanding and knowingness. It is also good for marriage and for happiness with children.",
    (10, 11): "This is a super-powerful success signature: you can work your way toward almost any goal you set, and it brings titles, honors, and renown, so it is especially strong in public and political charts (it tends to win elections at some point). The one caution is that it is not a trine, so what the 11th judges worth working toward is not always what is genuinely worth it. It reaches its best when it is anchored to a trine or supported by dharma yogas, so the goals you chase are truly your own.",
}

KHALA_PAIR_DESC = {
    (1, 3): "The 3rd fuses with the 1st, so the whole self and life path run on raw self-drive with no lucky breaks to lean on. This native knows exactly what they want and pushes at it under their own steam, indifferent to anyone outside their plans, and they have to make it entirely on their own merit. Self-development goes well while the effort holds, but the path swings up and down because nothing arrives by favor. The exam turns on sheer strength of character and personal ability: do they, in themselves, have what it takes to make it happen.",
    (2, 3): "The 3rd links to the 2nd, so the focus locks onto money and material responsibilities with a hard drive to acquire. Meeting those obligations burns enormous energy, so life runs in near-exhaustion followed by bursts of speed to catch up. Finances climb while the attention holds, then a single poor decision or lapse brings losses, giving the classic up-and-down rhythm around wealth. The test is responsibility and follow-through: can they come through, keep the promise, and manage the thing all the way to success.",
    (3, 4): "The 3rd joins the 4th, making this a moving-and-relocation combination of frequent self-chosen changes of residence out of boredom, frustration, or the pull of somewhere else. The 4th is also happiness, so they feel on top of the world while getting their way and applying themselves, then drop fast into unhappiness and frustration when they cannot. The happiness is a restless thrill rather than settled peace, so it never lasts, and home and emotional state both keep swinging. The test is simply how they feel about it: they quit when they do not feel like it and continue when it feels good.",
    (3, 5): "The 3rd fuses with the 5th, centering everything on their own creativity and inspiration in a narrow, intense self-focus with little interest in what anyone else creates. They push hard and creatively (marketing, advertising, blogs, videos), and because the 5th carries luck, results can come fast, but the moment the creative push stops the results fall away. Children show the same swings, often from too much energy poured in or attention that keeps shifting. The test is intelligence: a lapse in understanding causes the mistake, and the mistake causes the fall.",
    (3, 7): "The 3rd links to the 7th, and since both are social houses the native is usually socially able and good at relating. If the planets are afflicted it turns strongly self-willed in partnership, insisting on their own way, self-centered, willing to use people to reach their desires and struggling to give the partner equal attention. Marriage is not stable here: it works while actively worked at, but the instant they stop something goes wrong or the partner loses interest, so relationships run up and down and there may be more than one. The test is managing another person: the social and communication skill to get the other to do what the goal needs.",
    (3, 9): "The 3rd joins the 9th, so the native loses the 9th's divine hand of luck and grace and life becomes far more effort-dependent, reaching exactly as far as their own work carries it. But the 9th is the house of wisdom, so their skill and capability run markedly higher: talented, intelligent, and less prone to mistakes than most Khala natives. Relationships with teachers and gurus swing up and down, since they will debate, argue, even turn disrespectful once the teacher's ideas stop matching their own. The test is wisdom and cultivated experience: are they wise enough, seasoned enough, for the situation in front of them.",
    (3, 10): "The 3rd links to the 10th, which sit in a 6-8 relationship, focusing the native on career, karmas, and large ambitions. Success comes while they push and drops when they stop, with no lucky breaks to backstop it, and the core problem is inconsistency: the 3rd's short-term will is not the steady dharmic fire, so they keep changing jobs, work, ambitions, and even loyalties and bosses. Finding a steady path to success through the career is genuinely hard. The test, much like the 1st, is whether they can handle it and are strong enough, since the 10th is the ultimate house of the responsible party.",
    (3, 11): "The 3rd fuses with the 11th, the best of the Khala pairs, since both are self-will houses that pair naturally (the 3rd is what I want to do right now, the 11th is what I want to get right now) and it often forms a viparita yoga as well. They are excellent at short-term goals and very capable of getting what they want when they want it, but there is no long-term continuity: once attained they are bored and need the next thing, desires keep shifting, and the excitement eventually curdles into an under-the-surface frustration. Nothing comes free, they only get it while actively working it. The test is whether they can hold focus long enough to truly fulfill a hope or desire in a significant way.",
}

DAINYA_PAIR_DESC = {
    (1, 6): "The 6th lord and Lagna lord trade signs, delaying your sense of place and purpose in the world and dragging down the self-respect you build. Once you finally know what you want, fresh obstacles block the way, often financial, or a slower mind or body (even a learning difficulty) that makes every bit of self-improvement harder and longer. A chronic self-doubt runs under everything (am I good enough for this, is this really what I should be doing), and in the worst cases the native decides the effort is not worth it and simply drifts. This is one of the harder 6th-house exchanges because of its 6-8 geometry, but the disappointment stays subtle and livable rather than catastrophic.",
    (1, 8): "The 8th lord and Lagna lord exchange, the hardest of all Dainya yogas. There is massive instability and no stable foundation, a life of constant change and roving where no matter where you go, a huge break drops you somewhere completely different. Jaimini's reading of the lagna and 8th lords crossing is a person poor and roving, and that is exactly the flavor. The image is walking your path when the ground opens and swallows you, and the only way forward is deep surrender.",
    (1, 12): "The 12th lord and Lagna lord exchange, so you surrender your own path and self-purpose to a greater force and are never quite in charge of your own life (family, institutions, the body, or plain weakness steer it). On the concrete side you are a habitual spender, happy to pay whatever you want in the moment and poor at saving. In strong dignity this becomes a conscious devotion of the whole life to a higher spiritual power. In weakness it collapses into loss of clear vision, escapism, and addiction, following the path of least resistance.",
    (2, 6): "The 6th and 2nd lords exchange, fusing struggle with money into steady financial misery. You must work very hard just to meet your bills, it is hard to get well paid for what you do, and health problems and obstacles keep triggering fresh expenses and debts. No matter how hard you push, at best you maintain and never quite get ahead, because every scrap of surplus is eaten by the next problem. Both are material houses, so this is among the mildest Dainya exchanges, with no big disabling setbacks.",
    (2, 8): "The 8th and 2nd lords exchange, both money houses, producing sharp instability with your money and with the things you need. What you expect to receive from a venture or marriage arrives unstably, late, short, or not at all, and need-driven efforts get disrupted at the last moment (the company folds right before your raise, you are fired right before promotion). You can never quite trust that you will get what you need. If the 5th or 9th lords are involved with good dignity, the same instability can flip into unexpected financial surprises.",
    (2, 12): "The 12th and 2nd lords exchange, draining your resources through endless expenses, but here it is because responsibilities keep demanding money, so the moment extra cash appears something calls for it. It is hard to build any base of security, and in group ventures you are always the one putting in the extra money and hours. You end up carrying more of the financial load than everyone else. Badly afflicted, the frustration tips into real irresponsibility, dodging and mishandling duties until they snowball into ever-greater stress.",
    (3, 6): "The 6th and 3rd lords exchange, so every attempt to build a skill or improve yourself hits an obstacle or delay. Train for a physical skill and you injure yourself, cannot afford the school you want and settle for a lesser one, or fight a slow memory and a restless mind that will not let talent grow. The weak link is the exact point in any venture where you must level up your ability, and that is where it stalls. Often this shows as a real inability to productively hone what you are trying to master.",
    (3, 8): "The 8th and 3rd lords exchange, a surprisingly difficult pairing (and not a Vipareeta reversal, despite the common claim). The skills and small things you patiently refine get disrupted, decisive action meets a closed door, and you feel cheated as opportunity vanishes right when you are ready. The athlete is injured the week before the event, the lecturer falls ill on arrival, tasks fall through as you look into them. Risk of travel and sports accidents is raised, and if the Ascendant lord is caught up in it, serious accidents become likely.",
    (3, 12): "The 12th and 3rd lords exchange, weakening the will and the ability to exert yourself toward what you want. Talents that should grow through practice instead wither or are lost, sometimes suddenly and tragically (the cyclist whose strength simply left his legs, the pianist whose fingers are smashed), and there can be learning difficulty in the very areas you love. Among siblings, neighbors, and associates you are the one whose voice is heard least and who always sacrifices your own ideas. Focus wavers and dabbles rather than building.",
    (4, 6): "The 6th and 4th lords exchange, making it a hard struggle to secure even the basics of happiness and your fair share on earth. Any abundance costs enormous work and arrives at maybe a tenth of what the effort warranted, with long delays to comfort and to happiness itself. Because the 4th is an angle, this bites harder than the money pairs, and natives can turn dry and grudging over time, questioning whether it is even worth living here. Things end up feeling joyless, never quite happy enough to justify the labor.",
    (4, 8): "The 8th and 4th lords exchange, both moksha houses in mutual trine, which makes it generally the mildest of the harsh 8th-house pairs. It brings strong instability of residence, moving place to place and even country to country as circumstances keep forcing relocation (move for a relationship that ends, for a job that ends), with a lingering sense of no place in the world. With good dignity it can turn into strong spiritual aspiration or two homes you travel between. With bad dignity, or the 1st, 6th, or 12th lord stuck in, watch for dire vehicle accidents.",
    (4, 12): "The 12th and 4th lords exchange, so home, mother, and happiness cost more than they ever return, with things that should make you glad vanishing prematurely or draining more than the comfort they give. You are the one who must surrender comfort and can find contentment only in a state of surrender. Because it is a trine the lords are usually friends, which redeems it somewhat. The higher outcome, real happiness in spiritual growth, only shows up when the chart also carries the Dharma Rajyogas as a foundation.",
    (5, 6): "The 6th and 5th lords exchange, bringing misery through creativity and children. It is a struggle to have children, or they arrive with problems and hard lives, and creative works fall into disrepair or never get finished. Creation is fun at the start but the exchange obstructs the long labor of completing and maintaining it, so the weak link is sustaining the inspiration to the end. Such natives are often quite sexual yet unwilling to shoulder the responsibility of children, and are at a loss finishing what they begin.",
    (5, 8): "The 8th and 5th lords exchange, destroying consistency of effort, inspiration, and action. Passion flares this week and is gone the next, and the moment you finally become steady, life pulls you away and the crisis hits. It is hard to shine, to become your best, or to hold a stable feeling about a partner, a job, or a purpose. Around children it can indicate tragic situations (miscarriage, difficulty conceiving, tragedy around a child), intensifying when the planets are afflicted.",
    (5, 12): "The 12th and 5th lords exchange, making children and creative ventures costly and less fulfilling than they should be. A child's problems drain your money, time, and worry, creative works cost more and satisfy less, and you lose constancy and long-term focus (the 5th is where we stay devoted). You must give up more of your creative vision than your co-creators and end up miserable about the whole process. Being a 6-8 relationship, the changes tend to be sudden and radical on the relevant dashas, leaving you a little more lost about direction.",
    (6, 7): "The 6th and 7th lords exchange, a difficult pairing that brings misery through the people you try to do something important with: losses, divorce, serious quarrels, and lawsuits with former partners, plus obstacles caused by the spouse. From the 7th the 6th is the house of loss, so the work a relationship costs is never repaid by the joy it gives. The 7th also rules long journeys, so travel turns risky (accidents, breakdowns, robbery) and the trip's toll outweighs its reward. Negotiations reliably go against you, and sexual diseases are possible.",
    (6, 8): "The 6th and 8th lords exchange, a double dusthana that compounds misery rather than cancelling it (this is no Vipareeta reversal, and both houses are demolished). Obstacles cause bigger breaks and breaks cause bigger obstacles, so problems escalate instead of resolving, and this is a strong indicator of chronic disease, especially when a planet ruling the body is involved. Trying to extract worth from others costs more than it is worth, winning the court case but paying the lawyer more than the settlement. Whatever you try to fix turns much larger and often insurmountable, because the 8th destroys where the 6th merely stunts.",
    (6, 9): "The 6th and 9th lords exchange, so life repays your faith at a discount. You follow the path that works for everyone else and get only half the reward, feeling robbed and over-taxed by life's toll, believing in heaven but reaching only purgatory. Expectations formed from your beliefs keep failing to come true, always landing you partway and never at the actual goal. This is not disastrous like an 8th-house pair, because faith in life is stunted rather than destroyed.",
    (6, 10): "The 6th and 10th lords exchange, the best of the 6th-house pairings since both are material houses. You can slowly and tediously manage your career and material responsibilities, but only through hard, drudging, joyless work. You always fall one rung short of the topmost aim, striving for manager and landing assistant manager, and even that costs a great deal. Livable and productive, but a life of much hard work and little respect.",
    (6, 11): "The 6th and 11th lords exchange, delaying the fulfillment of your desires and demanding far more work to reap them. When the reward finally arrives, the effort outweighed it or it simply is not as good as you hoped. As trophies and titles it always falls short, silver or bronze but never gold, or you win gold and then lose it to a scandal or disqualification. Because the 11th is the 6th-from-6th, this carries the delay signature rather than pure destruction, so the very reason you are doing something is what falls short.",
    (6, 12): "The 6th and 12th lords exchange, a double dusthana and a serious troublemaker that never cancels out. Obstacles and delays produce losses and expenses, and those losses produce more obstacles, a vicious loop that feeds itself. The money and effort you pour in to fix things are simply thrown in the trash, wasted resources with nothing to show. The moment you dig in and fight hardest for something is exactly when it is completely lost, dues paid and nothing gained.",
    (7, 8): "The 8th and 7th lords exchange, among the very hardest for an ordinary person because the 7th is an angular lord in a 2-12 loss relationship with the 8th. It brings breaks and instability in love shot through with loss: it is nearly impossible to find a stable partner, good relationships fall into crisis and end, and you feel cheated by betrayal or infidelity. There is a strong hidden element, a secret of the partner or a truth you hide from yourself that quietly dooms the bond. Very hard to marry or to hold a long-term partnership together.",
    (7, 12): "The 12th and 7th lords exchange, running both relationships and desires at a deficit. The classic signature is an affair, which is itself a loss of partnership, and everyone loses, since your time and energy get divided among two people for no extra return. On deals you come out on the short end, buying above market and selling below, and long-distance journeys are not worth the reward. Predict the affair only with debilitation (especially a debilitated Venus); with solid dignity it reads instead as an ill or draining partner, and if the 1st lord is involved, foreign travel that wrecks your health.",
    (8, 9): "The 8th and 9th lords exchange, so you feel cheated by life itself. As you follow your beliefs and do what you think is right, something upsets it and you learn not to trust that any plan, book, or effort will get you where you want to go, and lives end up way off target with shocking tragedies. Because the 9th is law and the 8th breaks it, there is a tendency to break laws, only the petty ones with good dignity (speeding, taxes, building codes) while following a higher law. Badly afflicted, it can produce a genuine outlaw with no regard for anything sacred.",
    (8, 10): "The 8th and 10th lords exchange, both angular, bringing career instability and setbacks. Success takes far more effort and yields bigger disappointments, you feel robbed as your achievements go uncredited or someone else takes the credit, and the work history turns chaotic and short-stretch (a year on, a year off, jobs lost). It becomes hard to fulfill your obligations, disappointing others and yourself. With well-placed planets it can flip into an unexpected rise through inheritance, the classic case being an exalted 10th lord in the 8th.",
    (8, 11): "The 8th and 11th lords exchange, so the hopes and payoffs you are really working toward fail to satisfy. You get tricked, deceived, or cheated, and the reward you reach for turns out rotten or hollow, the carrot mushy in your hand or so hard it breaks your teeth. It may still work out for some other reason you can find happiness with, but the personal motive that drove you rarely pays off. Fulfillment, when it comes, arrives by a route you never intended.",
    (8, 12): "The 8th and 12th lords exchange, a double dusthana but mutually trinal, which makes it the least troublesome of the 8th-house exchanges (Parashara approved the 12th lord in the 8th, the one dusthana-in-dusthana placement he liked). The main downside is that expenses are impossible to plan, sudden costs blowing the budget amid swings of energy and money, and what a partner promises to bring often fails to materialize, or worse, they cheat you when dignity is poor. With good dignity, which is common here, it fosters deep contemplation, strong spiritual or research work, and a genuine attitude of surrender. It is still compounded misery, not a lucky reversal.",
    (9, 12): "The 12th and 9th lords exchange, which the teacher rates among the least bad of the 12th-house pairings, though still problematic. Your belief system simply does not pay off as well for you, the same or greater effort yielding less progress, and serving a guru or teacher disappoints. Living lawfully still gets you shortchanged, even by judges, juries, and lawyers, and badly afflicted it turns you into a covert cheater who does not get caught. The best resolution is a deep surrender, an openness to whatever truth life actually shows you.",
    (10, 12): "The 12th and 10th lords exchange, a heavy interchange because the 10th is load-bearing. Career investment fails to pay off (the doctor whose training and office are wiped out by one malpractice suit), fulfilling your responsibilities takes far more out of you, and you lose authority and earned respect, the least authoritative in the room even when you know the most. You are rarely the final decision-maker, and when you try, others usurp or disregard you. Badly afflicted you shirk duties and struggle to take work to its highest level, mistaking good enough for as done as possible.",
    (11, 12): "The 12th and 11th lords exchange, so your hopes cost far more time, energy, and money to reach and disappoint on arrival, with the hope often lost along the way into a creeping hopelessness (a marriage that feels emptier the longer it runs). You lose your long-term aim and direction. With strong dignity and genuine spiritual factors this can mature into the rare capacity to surrender hope itself, since hope and fear are both ego-born, and it can flower into a successful community or ashram life.",
}


def _pair(house_a, house_b):
    return tuple(sorted((int(house_a), int(house_b))))


def describe_exchange(house_a, house_b):
    """Specific reading for an exchange between two houses, or None.

    Looks up the sorted house pair across all three type tables (a pair belongs
    to exactly one type). None if either house is out of 1..12 or the pair is a
    degenerate same-house (not a real 2-house exchange).
    """
    key = _pair(house_a, house_b)
    if key[0] == key[1] or key[0] < 1 or key[1] > 12:
        return None
    for table in (MAHA_PAIR_DESC, KHALA_PAIR_DESC, DAINYA_PAIR_DESC):
        if key in table:
            return table[key]
    return None
